title: The wareHHOuse
description: The home of the DiSk++ and ProtoN computational codes
theme: just-the-docs

baseurl: ""
url: https://wareHHOuse.github.io

permalink: pretty

defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

math: mathjax


