title: The wareHHOuse
description: The home of the DiSk++ and ProtoN computational codes
theme: just-the-docs

baseurl: ""
url: https://wareHHOuse.github.io

permalink: pretty

defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"

